<script>
    import featured_article_graphic from '$lib/images/featured-article.png';
    import tear_south_base_offwhite from '$lib/images/tear-south-base-offwhite.png';
</script>

<div class="my-1 md:my-0">
    <img class="tear-north" src={tear_south_base_offwhite} alt="">
    <section class="bg-[#F8F1E7] px-4 py-4 md:py-8 md:flex md:justify-center md:content-center md:items-center gap-4 relative z-50">
        <div class="flex flex-col sm:mx-36 md:mx-44 lg:mx-64 xl:mx-96">
            <h1 class="pb-6 text-3xl">“I did a thing:” The science behind your impulse buys</h1>
            <p class="text-sm">Written by: Ysabel Dinsay | Published on: April 24, 2024</p>

            <img class="pb-4 m-auto" src={featured_article_graphic} alt="Featured Article (Collage of loose pastel blouses)" width="458" height="407">

            <p class="pb-4 text-base text-left">Last week, I walked into an Adidas to kill some time. I like to work out and it was time to buy a more supportive sports bra soon. Time to canvas, I thought. So I walk into the women’s section and that’s when I see it in my favorite shade of muted blue. I read the tag and like it’s fate, I see the words “high-support.” It’s just what I need – but wait, what bottoms could I possibly wear with this beautiful blue? Certainly not the regular black or gray I already have. I should probably check out the matching shorts I don’t need! Just like clockwork, a staff member approaches me and tells me that if I download their app, I can get 15% off. Needless to say, I bought a whole set.</p>
            <p class="pb-4 text-base text-left">That is an impulse buy. And research says these unplanned purchases we make on a whim represent between 40 to 80% of all purchases <span><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8206473/"><span><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8206473/">[5]</a></span></a></span>.</p>
            <h2 class="pb-6 text-2xl font-bold">What drives us to make impulse buys?</h2>
            <p class="pb-4 text-base text-left">What I didn’t tell you about that store was that it smelled good. It had high ceilings with warm bright lighting. On the way to the fitting room, I walked through a tunneled archway decorated with fake vines and neon light accents specifically made for Instagram stories or a day-in-the-life TikTok. All this to say five senses were being seduced, to the dismay of my willpower and wallet.</p>
            <p class="pb-4 text-base text-left">The best retail companies put so much work into store design and product layout because they know the value of the customer’s experience is infinitely more important than the product’s value <span><a href="https://www.sciencedirect.com/science/article/abs/pii/S0969698920314260">[7]</a></span>. And this hold on our senses is generally why most impulse purchases still happen in brick-and-mortar stores. But sensory experience is only one way to tap into our emotions. </p>
            <h3 class="pb-6 text-xl font-bold">A sense of urgency</h3>
            <p class="pb-4 text-base text-left">Before I bought the set, I left the store in search of other athletic apparel I might like better. In my brief walk, I thought the following, “What if someone else takes it?” “Will they even still have this style and size a week from now?” Before I knew it, I had promptly turned around to buy the damn thing.</p>
            <p class="pb-4 text-base text-left">This is exactly what brands are trying to accomplish when they use these phrases, “Limited-time offer” or “Limited stocks available.” Look no further than the flash sales we see on Shopee and Lazada. They happen like all the time but that countdown plays into our fear of missing out so well that we fall for it every single time because “what if I never get a deal this good again?”</p>
            <p class="pb-4 text-base text-left">These deals are also helpful in decreasing what is known as the pain of paying <span><a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/mar.21825">[4]</a></span>. Studies show that it physically hurts us to give up the precious resource of money that we may look for other reasons to justify the purchase (e.g. deals, rewards, points, etc.) that allow us to feel the uninhibited dopamine hit of a purchase <span><a href="https://www.jstor.org/stable/10.1086/338209?origin=JSTOR-pdf">[2]</a></span>. But, there is one more aspect that retail companies have the least control over. However, it is arguably the most powerful one because you sustain it. It’s your personality, babe. </p>
            <h3 class="pb-6 text-xl font-bold">Your personality</h3>
            <p class="pb-4 text-base text-left">Research has shown time and again that impulsive buyers tend to have low self-esteem, negative moods, and high levels of anxiety and depression  <span><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8206473/">[5]</a></span>.  Let’s face it buying makes us feel good. In fact, compulsive shoppers derive more joy from buying than actually owning the item. Hence why retail therapy exists wink wink. </p>
            <p class="pb-4 text-base text-left">There is so much more to an item than what meets the eye. Our belongings can signal status, earn respect, and connect us to others. Trends exist and thrive because as social beings, we will always want to be a part of something. </p>
            <p class="pb-4 text-base text-left">Take the infamous set I bought. I didn’t buy it just because it was cute and on sale. I bought it to signal that I prioritize fitness. I’m with the gym girls because I look the part. I bought it to show my status. Adidas is not cheap and I had enough money to drop on brand-new clothing I didn’t need. The sooner we realize how these very real human needs are imparted to an item that will not necessarily fulfill that void in us, the sooner we will overcome the dangerous cycle of impulse buying.</p>
            <h3 class="pb-6 text-xl font-bold">The smarter shopper</h3>
            <p class="pb-4 text-base text-left">I’m not saying that all impulse buys are terrible and we should punish ourselves for it. But the reality is most of these purchases don't make us happier in the long run. They sit in our closet or storage room until we finally decide to get rid of them. Compared to 15 years ago, the average person today buys 60% more items of clothing while only keeping them for half as long as they used to <span><a href="https://cdn.businessoffashion.com/reports/The_State_of_Fashion_2019_v3.pdf">[1]</a></span>. And where do they go? Research shows that 20% of global water pollution comes from the fashion industry <span><a href="https://earth.org/statistics-about-fast-fashion-waste/">[3]</a></span>. The waste that the beauty industry alone produces 72 square meters of forests every year to make way for landfills <span><a href="https://www.forbes.com/sites/lucysherriff/2019/09/17/the-minimalist-beauty-company-tackling-the-industrys-waste-problem/?sh=4dcd2e804326">[6]</a></span>. And at the rate our planet is going, we should all be challenging ourselves to do a little better by being smarter shoppers.</p>
            <p class="pb-4 text-base italic text-left">P.S. After I finished this article, I did some cardio in my muted blue Adidas set.</p>

            <!-- <ol class="" type="1">
                <li>Amed, Imran, and Achim Berg. McKinsey & Company, Business of Fashion, 2019, pp. 1–99, The State of Fashion 2019. </li>
                <li>Baumeister, Roy F. “Yielding to temptation: Self‐control failure, impulsive purchasing, and consumer behavior.” Journal of Consumer Research, vol. 28, no. 4, Mar. 2002, pp. 670–676, https://doi.org/10.1086/338209. </li>
                <li>Igini, Martina. “10 Concerning Fast Fashion Waste Statistics.” Earth.Org, Earth.Org, 4 Mar. 2024, earth.org/statistics-about-fast-fashion-waste/. </li>
                <li>Reshadi, Farnoush, and M. Paula Fitzgerald. “The pain of payment: A review and research agenda.” Psychology &amp; Marketing, vol. 40, no. 8, 9 May 2023, pp. 1672–1688, https://doi.org/10.1002/mar.21825. </li>
                <li>Rodrigues, Rosa Isabel, et al. “Factors affecting impulse buying behavior of consumers.” Frontiers in Psychology, vol. 12, 2 June 2021, https://doi.org/10.3389/fpsyg.2021.697080. </li>
                <li>Sherriff, Lucy. “The Minimalist Beauty Company Tackling the Industry’s Waste Problem.” Forbes, Forbes Magazine, 29 June 2021, www.forbes.com/sites/lucysherriff/2019/09/17/the-minimalist-beauty-company-tackling-the-industrys-waste-problem/?sh=5c38802e4326. </li>
                <li>Sohn, Yong Seok, and Man Ting Ko. “The impact of planned vs. unplanned purchases on subsequent purchase decision making in sequential buying situations.” Journal of Retailing and Consumer Services, vol. 59, Mar. 2021, p. 102419, https://doi.org/10.1016/j.jretconser.2020.102419. </li>
            </ol> -->
        </div>
    </section>
    <img class="tear-south" src={tear_south_base_offwhite} alt="">
</div>